version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.11.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn build
workflows:
  version: 2
  master:
    jobs:
      - test
